### ISSUE TITLE
Moving camera slowly

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1459] opened 2015-04-08 10:21 UTC
Hi,
i just to know whether it is a normal behavior or not.
my renderer is based on RajawaliVRRenderer.
when i put the phone on back, i mean it is stable, the camera moves slowly to right.
i don't set anything on onDrawFrame(GL10 glUnused)  method.

here is the code: just a simple skybox code.
		@Override
		public void initScene() {
			try {
				getCurrentScene().setSkybox(posx, negx, posy, negy, posz, negz);
			} catch (TextureException e) {
				e.printStackTrace();
			}
			super.initScene();
		}

is it normal behavior?

**Comment by ToxicBakery** [comment] 2015-04-08 12:18
You mean the camera is animating with rotation?

**Comment by uzman** [comment] 2015-04-08 13:19
yes, very slowly. maybe it rotates 3-5 pixel.

**Comment by ToxicBakery** [comment] 2015-04-08 14:08
Well 100% the camera does not rotate by itself. So the skybox is being told to rotate or you have set the camera to rotate itself. In either case this is too narrow of a picture into what you are doing to help. Please create a concise example that demonstrates your issue.

**Comment by uzman** [comment] 2015-04-08 14:17
i checked the latest sample (android studio). i removed the onDrawFrame method. it doesn't rotate.
it is ok.

but i am using eclipse project (Rajawali + RajawaliVR 9 months ago). 
i have just this code: it rotates by itself. i think i should move to android project.

public void initScene() {
try {
getCurrentScene().setSkybox(posx, negx, posy, negy, posz, negz);
} catch (TextureException e) {
e.printStackTrace();
}
super.initScene();
}

**Comment by jwoolston** [comment] 2015-04-08 15:54
It is probably rotating due to noise being picked up by the head tracking of the RajawaliVR project.

**Comment by uzman** [comment] 2015-04-08 18:40
i converted my project to android studio.
I'm using latest rajawali now.
camera rotates by itself. i think onRender method rotates it.
here is the RajawaliVRRenderer class:

public class RajawaliVRRenderer extends RajawaliSideBySideRenderer {
    protected HeadTracker mHeadTracker;
    protected HeadTransform mHeadTransform;
    protected float[] mHeadViewMatrix;
    protected Matrix4 mHeadViewMatrix4;
    private Quaternion mCameraOrientation;

    public RajawaliVRRenderer(Context context) {
        super(context);
        mHeadTransform = new HeadTransform();
        mHeadViewMatrix = new float[16];
        mHeadViewMatrix4 = new Matrix4();
        mCameraOrientation = new Quaternion();
    }

    @Override
    public void initScene() {
        super.initScene();
    }

    public void setHeadTracker(HeadTracker headTracker) {
        mHeadTracker = headTracker;

    }

    @Override
    protected void onRender(long ellapsedTime, double deltaTime) {
        mHeadTracker.getLastHeadView(mHeadViewMatrix, 0);
        mHeadViewMatrix4.setAll(mHeadViewMatrix);

        mCameraOrientation.fromMatrix(mHeadViewMatrix4);
        //mCameraOrientation.x *= -1;
        //mCameraOrientation.y *= -1;
        //mCameraOrientation.z *= -1;
        setCameraOrientation(mCameraOrientation);
        super.onRender(ellapsedTime, deltaTime);
    }

}

public class RajawaliVRActivity extends RajawaliActivity{
    private HeadTracker mHeadTracker;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mSurfaceView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
                | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
                | View.SYSTEM_UI_FLAG_IMMERSIVE);
        mHeadTracker = new HeadTracker(this);
    }

    protected void setRenderer(RajawaliVRRenderer renderer) {
        renderer.setHeadTracker(mHeadTracker);
        super.setRenderer(renderer);
    }

    @Override
    public void onResume() {
        super.onResume();
        mHeadTracker.startTracking();
    }

    @Override
    public void onPause() {
        super.onPause();
        mHeadTracker.stopTracking();
    }

}

**Comment by jwoolston** [comment] 2015-04-08 19:29
Yes, it is rotating because the head tracker is reporting movement from the Google Cardboard API.

**Comment by ToxicBakery** [comment] 2015-04-08 19:49
Closed as this is likely a bug or feature of RajawaliVR or the underlying Android VR support. It appears Rajawali is working as intended.

**Closed** 2015-04-08 19:48 UTC
Labels: Support

**Comment by jwoolston** [comment] 2015-04-08 19:59
If you wish to remove this you need to either calibrate the accelerometers or implement filtering, both of which are beyond the scope of this or any other Rajawali related repository at present. Please search online for information regarding this.
