### ISSUE TITLE
Postprocessing issue in LWP

### ISSUE THREAD

**Issue by itafraji** [Rajawali/Rajawali#1266] opened 2014-06-12 07:33 UTC
During testing of new postprocessing engine implemented in LWP I found issue which leads to crash of LWP.
Here are steps how to reproduce it. You should have live wallpaper using at least 1 render target.
1) run wallpapaper
2) set wallpaper
3) run it again
4) press back button
5) run it again - it will crash.

I try to investigate it but unfortunatelly I didn't manage to find from where exactly this comes.
I suspect that that problem is in onSurfaceChange which is called many times with diferent values of variable mSceneInitialized. There it reset or reload rendertargets. I sippose that in this particular case something is not reinitialized correctly. Then the fatal error is in onDrawFrame when RenderTarget.create is called. It says "Could not create frame buffer. Invalid operation.

**Comment by jwoolston** [comment] 2015-03-30 23:38
Marking this for @MasDennis to take a look at.

**Comment by jwoolston** [comment] 2015-04-01 08:29
This appears to be related to the memory leak, moving to 1.1.

**Comment by jwoolston** [comment] 2016-03-18 04:27
I have update the examples module to include several post processing examples. I am not able to reproduce this issue with those examples. If you can provide an apk or code which will cause this to happen, I can reopen the ticket.

**Closed by jwoolston** 2016-03-18 04:27 UTC
Labels: Info Needed, Review
