### ISSUE TITLE
problem: lighting changes when the camera moves

### ISSUE THREAD

**Issue by denoson** [Rajawali/Rajawali#2234] opened 2020-12-24 19:36 UTC
#### Rajawali Version or Branch
Hello!
In your sample (fog) light is not changed when I move camera. But when I change OBJ file to my object (with the same size) - the light (brightness or power) is changed when I move camera. When I return your object (road obj), the brightness of the light does not change again when moving.
I do not understand why light is changed if I replace OBJ file to my file. Why might this be happening?  I am not using animation for lights.

Material for ground:

```
        Material material = new Material();
        material.setDiffuseMethod(new DiffuseMethod.Lambert());
        material.setColor(color);
        material.enableLighting(true);
```

Light init:
```
        spotLight = new SpotLight();
        spotLight.setPower(40);
        spotLight.enableLookAt();
        spotLight.setPosition(0, 10, -1);
        spotLight.setLookAt(0,0,-10);
        spotLight.resetToLookAt();
        getCurrentScene().addLight(spotLight);
```

**Comment by contriteobserver** [comment] 2020-12-24 22:05
Having trouble reproducing this issue, what is wrong with this test renderer?
```
    class MovingSidewalk extends Renderer {
        public MovingSidewalk(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            SpotLight spotLight = new SpotLight();
            spotLight.setPower(3);
            spotLight.enableLookAt();
            spotLight.setPosition(0, 1, 1/4f);
            spotLight.setLookAt(0,-9,0);
            getCurrentScene().addLight(spotLight);

            Material material = new Material();
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setColor(Color.LTGRAY);
            material.enableLighting(true);

            for(int i=0; i<12; i++) {
                Object3D stone = new Plane();
                stone.setPosition(0,-i,(i%2==1 ? 1/16f : -1/16f));
                stone.setMaterial(material);
                getCurrentScene().addChild(stone);
            }

            getCurrentCamera().setUpAxis(Vector3.Axis.Z);
            getCurrentCamera().setPosition(5,-4,3);
            getCurrentCamera().setLookAt(0,0,0);
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            for(Object3D child : getCurrentScene().getChildrenCopy()) {
                if(child instanceof Plane) {
                    Vector3 pos = child.getPosition();
                    pos.y += deltaTime;
                    if(pos.y > 6) pos.y -= 12;
                    child.setPosition(pos);
                }
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
![2020-12-24](https://user-images.githubusercontent.com/17471201/103107228-12379700-45f1-11eb-815c-96ce30986f6a.gif)

**Comment by denoson** [comment] 2020-12-25 07:08
Hello, I make separated sample, withh 100% reproducing of my problem. The light changes its parameters. How to prevent the light from changing the parameters? I do not understand why light is changed. Why might this be happening? I am not using animation for lights.

How to reproduce:
```
    private SpotLight spotLight;
    private double speed = 6;

    @Override
    protected void initScene() {
        spotLight = new SpotLight();
        spotLight.setPower(20);
        spotLight.enableLookAt();
        spotLight.setPosition(0, 3, -1);
        spotLight.setLookAt(0,0,-10);
        spotLight.resetToLookAt();
        getCurrentScene().addLight(spotLight);

        getCurrentCamera().setPosition(12,12,-11);
        getCurrentCamera().setFarPlane(222);
        getCurrentCamera().setFieldOfView(80);
        getCurrentCamera().setLookAt(0,0,-10);

        Material material = new Material();
        material.setDiffuseMethod(new DiffuseMethod.Lambert());
        material.setColor(Color.LTGRAY);
        material.enableLighting(true);

        Sphere lightMarker = new Sphere(0.3f, 8, 8);
        getCurrentScene().addChild(lightMarker);
        lightMarker.setMaterial(material);
        lightMarker.setPosition(spotLight.getPosition());

        Sphere lightMarkerLook = new Sphere(0.3f, 8, 8);
        getCurrentScene().addChild(lightMarkerLook);
        lightMarkerLook.setMaterial(material);
        lightMarkerLook.setPosition(spotLight.getLookAt());


        int cubeSize = 20;
        for(int i = 0; i < 20; i++) {
            Cube cube = new Cube(cubeSize);
            cube.setPosition(i%2==1 ? 0 : 1, 0, -(cubeSize + 0.2f) * i);
            cube.setScaleY(0.02f);
            cube.setMaterial(material);
            getCurrentScene().addChild(cube);
        }
    }


    @Override
    protected void onRender(long ellapsedRealtime, double deltaTime) {
        super.onRender(ellapsedRealtime, deltaTime);

        for(Object3D child : getCurrentScene().getChildrenCopy()) {
            if(child instanceof Cube) {
                child.setZ(child.getZ() + speed*deltaTime);
            }
        }
    }
```


https://user-images.githubusercontent.com/11543733/103124500-043d5100-4699-11eb-9e50-c4fe5006b375.mp4

**Comment by contriteobserver** [comment] 2020-12-25 23:35
This issue is not a bug, it is a consequence of tradeoffs to enable real-time 3D graphics. GLSL fragments are linearly interpolated from vertex values, this works as long as the distances and normals to light sources do not change non-linearly across the face too much.

![untitled](https://user-images.githubusercontent.com/17471201/103143101-0ddcae00-46c5-11eb-9af9-697e22bffa6f.png)
Consider distance from a triangle vertex to a light at (2,0,1), the distance to the first and second vertices are `sqrt(1*1+1*1+1*1)`, and the distance to the third is `sqrt(3*3+1*1+1*1)`, now the distance to the middle of the hypotenuse is `sqrt(2*2+1*1+0*0)`, but linear interpolation gives `0.5*sqrt(11)+0.5*sqrt(3)`, close but not the same, and as we use distance squared for attenuation calculations, the effect is readily apparent. Incident angle for Lambert diffusion calculations is similarly non-linear. 

There are shading methods that address this limitation, `Fragment Point Lighting ` transforms the values to become closer to linear and then inverts the transform in the fragment shader, but this is too computationally intensive for realtime graphics in a mobile device.

So the workaround is to increase the number of vertices until the non-linearities are tolerable. Our `Plane` primitive has two parameters, 'segmentsW' and 'segmentsH' for this purpose, typically planes are used to model ground.. (example below) We should no add this to 'Cube', as it must remain a simple cube implementation, but we might consider also augmenting `RectangularePrism` with this capability.

```
    class CubeWalk extends Renderer {
        private ALight spotLight;
        private double speed = 6;

        public CubeWalk(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            spotLight = new SpotLight();
            spotLight.setPower(12);
            spotLight.enableLookAt();
            spotLight.setPosition(0, 3, -1);
            spotLight.setLookAt(0,0,-10);
            //spotLight.resetToLookAt();
            getCurrentScene().addLight(spotLight);

            getCurrentCamera().setPosition(12,12,-11);
            //getCurrentCamera().setFarPlane(222);
            getCurrentCamera().setFieldOfView(80);
            getCurrentCamera().setLookAt(0,0,-10);

            Material material = new Material();
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setColor(Color.LTGRAY);
            material.enableLighting(true);

            Sphere lightMarker = new Sphere(0.3f, 8, 8);
            getCurrentScene().addChild(lightMarker);
            lightMarker.setMaterial(material);
            lightMarker.setPosition(spotLight.getPosition());

            Sphere lightMarkerLook = new Sphere(0.3f, 8, 8);
            getCurrentScene().addChild(lightMarkerLook);
            lightMarkerLook.setMaterial(material);
            lightMarkerLook.setPosition(spotLight.getLookAt());


            int cubeSize = 20;
            for(int i = 0; i < 20; i++) {
                Object3D obj = new Plane(cubeSize, cubeSize,8,8, Vector3.Axis.Y);
                obj.setPosition(i%2==1 ? 0 : 1, 0, -(cubeSize + 0.2f) * i);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);
            }

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);

            for(Object3D child : getCurrentScene().getChildrenCopy()) {
                if(child instanceof Plane) {
                    child.setZ(child.getZ() + speed*deltaTime);
                }
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by denoson** [comment] 2020-12-26 10:14
Ok, thank you. Now I understand. But I have no such constructor:
`Object3D obj = new Plane(cubeSize, cubeSize,8,8, Vector3.Axis.Y);`

I use:
implementation 'org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar'

**Comment by contriteobserver** [comment] 2020-12-26 20:32
Prebuilt Rajawali packages are available from `jCenter`, the default repository for gradle.
Add this line to your (Module: app) build.gradle dependencies:
```
    implementation 'org.rajawali3d:rajawali:1.1.970'
```
Is there a reason the current release is not an option for you?

**Comment by denoson** [comment] 2020-12-28 14:40
Ok, thsnk you, I try to use the latest version: implementation 'org.rajawali3d:rajawali:1.1.970'
(yes, its worked)

**Comment by denoson** [comment] 2020-12-28 14:42
Thank you for help. But I can not compile your examples (I have several eerrors and dependenses). Can you send me link to APK with compiled examples?

**Comment by contriteobserver** [comment] 2020-12-28 23:09
Not being able to compile our examples sounds like a new issue. If you agree, please close this issue, and open a new one. 

Having one issue per issue helps us reduce support overhead as it makes it easier for others to search for answers.

**Comment by denoson** [comment] 2020-12-29 18:27
Please send me a link to the APK with examples.  I have different settings and versions, because of this, it did not work to compile. I don't think this is a problem with your code.

**Comment by denoson** [comment] 2021-01-02 10:09
Hello contriteobserver, can you send me link to APK with latest examples?

**Closed** 2021-01-06 07:57 UTC
