### ISSUE TITLE
The rotation gesture is the opposite. （ArcballCamera）

### ISSUE THREAD

**Issue by li96968510** [Rajawali/Rajawali#1756] opened 2016-09-01 03:53 UTC
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.566-SNAPSHOT@aar

#### Device and Android Version
huawei (version:6.0) / xiaomi note pro (version:5.0)

#### Summary
The rotation gesture is the opposite.  when i rotate it up but it down ,and left but right.

Note：the version of  org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar is normal.

**Comment by jwoolston** [comment] 2016-09-01 03:59
Closing as duplicate of #1629

**Closed by jwoolston** 2016-09-01 03:59 UTC
Labels: Bug
