### ISSUE TITLE
STL Loader not rendering properly.

### ISSUE THREAD

**Issue by abhijeetdutta** [Rajawali/Rajawali#1487] opened 2015-05-08 09:33 UTC
Hi,

I working on an android app which specifically requires to load different STL files.

I am able to load STL files but some of the files are not rendering properly.

Result I am getting on screen using Rajawali :
![screenshot_2015-05-08-14-36-19](https://cloud.githubusercontent.com/assets/6577008/7533899/f035aeee-f592-11e4-9c1f-2aa1df6603d1.png)

Actual Model : 
![screen shot 2015-05-08 at 2 49 39 pm 1](https://cloud.githubusercontent.com/assets/6577008/7533896/dd3afb46-f592-11e4-81ee-5dbf09c20686.png)

Please help how to solve this.

Many Thanks.

**Comment by abhijeetdutta** [comment] 2015-05-09 10:41
Please reply ...

**Comment by abhijeetdutta** [comment] 2015-05-11 04:07
@MasDennis @jwoolston  Somebody reply on this issue ..

**Comment by jwoolston** [comment] 2015-05-11 04:13
I am trying to buy a house at the moment and have a 6 year old and a 3 month old, while also having a day job. Needless to say this is consuming all of my time. I havn't replied because I havn't had anything constructive to say on the matter. The STL parser has been known to have problems with some STL files. We aren't sure why and we havn't looked because it hasn't been much of a priority. We have 3 people who work on this project, and two of us have families with small children. Unfortunately this is the nature of the framework.

**Comment by ToxicBakery** [comment] 2015-05-11 12:31
Its also worth noting neither of them actually wrote that parser. You should debug it and try to figure out why it is not working. It is likely a floating point issue or possibly it is missing indexes. Whatever it is, JS parsers seem to work with all models while ours works with most. I'm sure its an edge case issue which is why I suggest you check the floating point parsing.

**Comment by ToxicBakery** [comment] 2015-05-11 12:42
Duplicate of #1112

**Closed by ToxicBakery** 2015-05-11 12:42 UTC
