### ISSUE TITLE
Maximum number of textures for this material has been reached. Maximum number of textures is 0

### ISSUE THREAD

**Issue by ProjectFF** [Rajawali/Rajawali#1484] opened 2015-04-23 14:36 UTC
Just created a standard scene nothing special 

```
OpenGLRenderer﹕ Initialized EGL, version 1.4
OpenGLRenderer﹕ Enabling debug mode 0
org.rajawali3d.materials.textures.ATexture$TextureException: Maximum number of textures for this material has been reached. Maximum number of textures is 0
org.rajawali3d.materials.Material.addTexture(Material.java:887)
org.rajawali3d.scene.RajawaliScene.setSkybox(RajawaliScene.java:866)
org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:34
```

that results in  ... :

```
    Process: projectff.rajawalivr_tryout, PID: 27207
    java.lang.RuntimeException: This object can't render because there's no material attached to it.
            at org.rajawali3d.Object3D.render(Object3D.java:250)
            at org.rajawali3d.Object3D.render(Object3D.java:181)
            at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:1085)
            at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:971)
            at org.rajawali3d.renderer.RajawaliRenderer.render(RajawaliRenderer.java:423)
            at org.rajawali3d.renderer.RajawaliRenderer.onRender(RajawaliRenderer.java:413)
            at org.rajawali3d.renderer.RajawaliRenderer.onRenderFrame(RajawaliRenderer.java:388)
            at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onDrawFrame(RajawaliSurfaceView.java:221)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

```
import javax.microedition.khronos.opengles.GL10;

import org.rajawali3d.lights.DirectionalLight;
import org.rajawali3d.surface.IRajawaliSurfaceRenderer;

import org.rajawali3d.renderer.RajawaliRenderer;

public class RajawaliVRExampleRenderer extends RajawaliRenderer implements IRajawaliSurfaceRenderer {

	public RajawaliVRExampleRenderer(Context context) {
		super(context);
		res = context.getResources();
	}
	
	@Override
	public void initScene() {
		
		DirectionalLight light = new DirectionalLight(0.2f, -1f, 0f);
		light.setPower(.7f);
		getCurrentScene().addLight(light);
		
		getCurrentCamera().setFarPlane(10000);
		getCurrentScene().setBackgroundColor(0xdddddd);
		
		try {
			
			getCurrentScene().setSkybox(R.drawable.posx, R.drawable.negx, R.drawable.posy, R.drawable.negy, R.drawable.posz, R.drawable.negz);
			
		} catch(Exception e) {
			e.printStackTrace();
		}
		
	}

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override
    public void onTouchEvent(MotionEvent event) {

    }

    public void onDrawFrame(GL10 glUnused) {
		super.onRenderFrame(glUnused);
    }
}
```

**Comment by ToxicBakery** [comment] 2015-05-20 11:54
I believe @jwoolston was having this same issue after certain changes. I thought it was resolved but maybe it was held on something else.

**Comment by jwoolston** [comment] 2015-05-20 15:03
Yea I thought I had fixed this. What SHA-1 are you on?

**Comment by bennylu** [comment] 2015-07-20 23:56
I met this problem when I didn't call GLSurfaceView.setEGLContextClientVersion(2)
Hope this helps.

**Comment by changjiashuai** [comment] 2015-09-15 14:54
I hava same problem.please help!

**Comment by jwoolston** [comment] 2016-03-18 01:18
@ProjectFF @bennylu @changjiashuai Are any of you still seeing this issue? I have been unable to reproduce. I am closing for now, will reopen if any one can reproduce on latest `master`.

**Closed by jwoolston** 2016-03-18 01:18 UTC
Labels: Bug

**Comment by ThunderStick** [comment] 2016-04-21 02:15
Still having this problem, latest version of Rajawali implemented

`04-20 21:09:48.912 12690-12730/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 2007
                                                   Process: com.igottadroid.vrprime, PID: 12690
                                                   java.lang.RuntimeException: org.rajawali3d.materials.textures.ATexture$TextureException: Maximum number of textures for this material has been reached. Maximum number of textures is 0.
                                                       at com.igottadroid.vrprime.SplashRenderer.buildSky(SplashRenderer.java:130)
                                                       at com.igottadroid.vrprime.SplashRenderer.initScene(SplashRenderer.java:92)
                                                       at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:347)
                                                       at org.rajawali3d.vr.renderer.RajawaliVRRenderer.onSurfaceChanged(RajawaliVRRenderer.java:111)
                                                       at com.google.vrtoolkit.cardboard.CardboardViewJavaImpl$StereoRendererHelper.onSurfaceChanged(CardboardViewJavaImpl.java:931)
                                                       at com.google.vrtoolkit.cardboard.CardboardViewJavaImpl$RendererHelper.onSurfaceChanged(CardboardViewJavaImpl.java:716)
                                                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1519)
                                                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
                                                    Caused by: org.rajawali3d.materials.textures.ATexture$TextureException: Maximum number of textures for this material has been reached. Maximum number of textures is 0.
                                                       at org.rajawali3d.materials.Material.addTexture(Material.java:884)
                                                       at com.igottadroid.vrprime.SplashRenderer.buildSky(SplashRenderer.java:128)
                                                       at com.igottadroid.vrprime.SplashRenderer.initScene(SplashRenderer.java:92) 
                                                       at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:347) 
                                                       at org.rajawali3d.vr.renderer.RajawaliVRRenderer.onSurfaceChanged(RajawaliVRRenderer.java:111) 
                                                       at com.google.vrtoolkit.cardboard.CardboardViewJavaImpl$StereoRendererHelper.onSurfaceChanged(CardboardViewJavaImpl.java:931) 
                                                       at com.google.vrtoolkit.cardboard.CardboardViewJavaImpl$RendererHelper.onSurfaceChanged(CardboardViewJavaImpl.java:716) 
                                                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1519) 
                                                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240) `

**Comment by PopTudor** [comment] 2016-04-24 16:00
I can confirm it too.
I am trying to load a Plane on the screen when the user clicks a button
```java
@Override  
protected void onCreate(Bundle savedInstanceState) { ...
  mTextureView = (TextureView) findViewById(R.id.texture_view);
  mTextureView.setEGLContextClientVersion(2);
  mTextureView.setSurfaceRenderer(mRenderer);
  mTextureView.setSurfaceTextureListener(this);
  findViewById(R.id.cool_button).setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				RandomObject randomObject = new RandomObject(mRenderer);
				randomObject.setTexture(R.drawable.cool_texture);
				mRandomRenderer.onFavoriteClicked(randomObject);
			}
	});
}
```
Random object it will be a single object with textures/materials and other properties and in future it will be able to load many types of objects(3ds,primitives) but for now it should only be able to load a Plane with AMeshLoader for async loading in Renderer
Here is RandomObject:
```java
public class RandomObject implements Comparable<RandomObject > {
	private int drawingPosition;
	private Renderer renderer;
	private Material material;
	private Texture texture;
	private Object3D object3D;
	private AMeshLoader loader;
	private int tag;


	public RandomObject (Renderer renderer) {
		this.drawingPosition = 0;
		material = new Material();
		material.enableLighting(true);
		material.setDiffuseMethod(new DiffuseMethod.Lambert());
		material.setColor(0);
			object3D =  new Plane(5, 5, 1, 1);
			object3D.setTransparent(true);
	}

	public void setTexture(int resourceID) {
		tag = resourceID;
		texture = new Texture("Texture_"+String.valueOf(tag), resourceID);
		try {
			material.addTexture(texture);
			object3D.setMaterial(material);
		} catch (ATexture.TextureException e) {
			e.printStackTrace();
		}
	}

	public AMeshLoader getLoader() {
		if (loader == null){
			loader = new AMeshLoader("") {
				@Override
				public Object3D getParsedObject() {
					return object3D;
				}
			};
		}
		return loader;
	}
	// other getters
     // compareTo by tag
}

```
And in Renderer I'm trying to do this
```java
Object3D loadedObject;
@Override
	public void onModelLoadComplete(ALoader loader) {
		Log.d(TAG, "onModelLoadComplete: ");
		final AMeshLoader obj = (AMeshLoader) loader;
		final Object3D parsedObject = obj.getParsedObject();
		parsedObject.setPosition(Vector3.ZERO);
		loadedObject = parsedObject;

		getCurrentScene().clearChildren();
		getCurrentScene().addChild(loadedObject);
	}

	@Override
	public void onFavoriteClicked(FaceObject object) {
		RandomObject faceObject = new RandomObject(this);
		faceObject.setTexture(object.getTag());
		loadModel(object.getLoader(), this, randomObject.getTag());
	}
```
I had problems sending the click event from UI to OpenGL and I am trying here to do it with a callback (although I'm not sure if it works). The above code worked with SurfaceView but I had to switch to TextureView and now it's broke. Do you have any suggestions on how to send a model from UI to the renderer more properly ? or am I on the right path with callbacks ?
