### ISSUE TITLE
Missing materials when adding Object3D to scene after initScene()

### ISSUE THREAD

**Issue by Haargeeel** [Rajawali/Rajawali#1291] opened 2014-08-05 16:40 UTC
Hey guys,
If I create my Object3D in initScene() everything is working quite well, but I don't want to wait until everything from my model is loaded. So I tried adding the Object3D to the scene, which is already initialised. But now I'm missing some, not all, of my textures. Well, I think I'm not just missing the textures but the whole materials.
Does anyone know this problem?

**Comment by jwoolston** [comment] 2015-03-24 18:07
This may have been resolved when brought async parsing into the mix. Please comment if this is still an issue and I will reopen.

**Comment by jwoolston** [comment] 2015-03-24 20:46
I am reopening this issue as I was just now able to recreate it.

**Comment by jwoolston** [comment] 2015-03-24 20:47
In my case this is with phong shading on a basic color material. Does the MTL file in your OBJ specify any specular effect @Haargeeel ?

**Comment by jwoolston** [comment] 2015-03-24 21:01
Doing some looking at the shader output of the material, in the case of adding after initScene, the lighting information is not being added into the shader code for compilation.

**Comment by Haargeeel** [comment] 2015-03-24 23:12
First of all good to see that I'm no forgotten here.
But I have to say I can't really remember everything I was struggling with. 
I didn't use the OBJ Loader. I wrote my own JSON Loader but it was very similar to the OBJ Loader. As you can see in the first image I put several effects in my JSON files. I'm 100% sure there are specular effects among them.
It seems you heading the right way with your last comment. I'm looking forward to any results but sorry I can't really describe my problem anymore. Maybe I take a look in the next days.

Thanks for investigating this problem @jwoolston

**Comment by jwoolston** [comment] 2015-03-31 20:50
Turns out what I thought was reproducing the issue was me forgetting to enable lighting. Major face palm moment. In any case, I'm pretty sure whatever issue was there, was resolved with the lazy initialization so I am closing this for now. If someone can reproduce it, we can revisit the issue.

**Closed by jwoolston** 2015-03-31 20:50 UTC
Labels: Bug
