### ISSUE TITLE
Live Wallpaper Memory Leak on Changing Textures on Runtime

### ISSUE THREAD

**Issue by abhishekBansal** [Rajawali/Rajawali#1336] opened 2014-12-24 16:52 UTC
Ok, I have seen many previous posts about this here but none of them actually helped. I am building a LWP using Rajawali which requires change of texture on a quad at runtime when user changes prefs. After changing texture a few times it crashes with out of memory errors. Also at few times i see black screen in preview mode or in live mode. 

```
java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
            at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:452)
            at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:482)
            at rajawali.materials.textures.ASingleTexture.setResourceId(ASingleTexture.java:93)
            at rajawali.materials.textures.Texture.<init>(Texture.java:32)
            at com.rrapps.Renderer.initScene(InfiniteTunnelRenderer.java:55)
            at rajawali.renderer.RajawaliRenderer.onSurfaceChanged(RajawaliRenderer.java:426)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

here is how i am changing texture when user changes shared preferences

```
private void _handleTextureChange() {
        int currentTextureNo = TApplication.SettingsInstance.getCurrentTextureNo();

        if(currentTextureNo == -1) {
            Log.e(LogTag, "Wrong texture Id(-1) from shared prefs");
        }

        // remove existing texture
        ATexture existingTexture;
        if(mMaterial != null) {
            existingTexture = mMaterial.getTextureList().get(0);
            mTextureManager.removeTexture(existingTexture);

            ATexture newTexture;
            int drawableId = 0;
            switch (currentTextureNo) {
                case 1:
                    drawableId = R.drawable.t1;
                    break;
                case 2:
                    drawableId = R.drawable.t2;
                    break;
                case 3:
                    drawableId = R.drawable.t3;
                    break;
                case 4:
                    drawableId = R.drawable.t4;
                    break;
                default:
                    drawableId = R.drawable.t2;
                    break;
            }

            newTexture = new Texture(TextureName, drawableId);
            try {
                mMaterial.addTexture(mTextureManager.addTexture(newTexture));
            } catch (ATexture.TextureException e) {
                Log.e(TApplication.LogTag, "Couldn't change texture " + currentTextureNo);
                e.printStackTrace();
            }
        }
    }
```

my onSurfaceDestroyed function

```java```
    @Override
    public void onSurfaceDestroyed() {
        super.onSurfaceDestroyed();
        for(ATexture texture : mMaterial.getTextureList()) {
            texture.shouldRecycle(true);
        }
    }
```
I am stuck on this from past few days please point me right direction. Also I am right now using `SharedPreferenceListener` in my Renderer which seems to be not a good idea but I am not sure how to apply @ToxicBakery 's solution in my case. I even tried that but it was giving me different settings in preview and live mode, which anyways is the case right now too.

Let me know if more information is required from my side. I am working with latest code and I checked with Android Studio memory profiler and its confirm that memory is constantly increasing on changinf textures.

Thanks

**Comment by jwoolston** [comment] 2015-03-14 19:46
There seems to be an annoyingly persistant memory related bug that none of the developers have been able to reproduce. We have had some credible reports with information pointing to a cause so we do accept that the existence of such a bug is likely, and it is in the list of tasks for the next milestone. @ToxicBakery's write up on using the preference listener is pretty straight forward and I have used it plenty of times so I know its valid, but it does assume you are familiar with Android lifecycle. You also must be 100% certain that no other listeners are registered.

 At least part of the problem, especially on devices running dalvik, seems to be that the GC is a bit lazy when it comes to recovering a bitmap that is no longer needed, so the new bitmap is allocated prior to the old one being freed.

**Comment by abhishekBansal** [comment] 2015-03-15 06:29
I can give u a sample reproducing the problem if you need. 
Let me know.

**Comment by ToxicBakery** [comment] 2015-03-15 14:12
I think this was not an issue then became an issue again with the new texture manager implementation. @abhishekBansal can you please run your sample, open the wallpaper settings, then go back to the home screen. After this, force a system GC and then dump the hprof and post it as a gist. I can throw it into MAT and determine exactly what caused the leak.

For reference on how to force gc and dump hprof:
![ddms-toolbar](https://cloud.githubusercontent.com/assets/1614281/6656305/bf71b4b8-cafb-11e4-8100-924b3d2d2265.png)

**Comment by jwoolston** [comment] 2015-03-31 00:31
Moving to Bombshell.

**Comment by jwoolston** [comment] 2016-03-18 23:13
I have started profiling this pretty heavily and while I can point to many wasteful allocations in Rajawali, I can not make it crash from texture changes. I believe what is happening here is you are either trying to allocate massive textures. Some life cycle improvements have been made since this issue was created and perhaps they fixed the issue. If you wish to email me a debuggable apk that demonstrates this, I can take a second look at it.

**Closed by jwoolston** 2016-03-18 23:13 UTC
Labels: Bug
